name: Deploy to Text Summarization Demo Space
on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install huggingface_hub
        run: pip install huggingface_hub
        
      - name: Configure Hugging Face CLI
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python -c "from huggingface_hub.hf_api import HfApi; HfApi().set_access_token('$HF_TOKEN')"
          
      - name: Deploy to Text Summarization Demo Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          # Space name is set to your specific repository
          SPACE_NAME: "hwang2006/text-summarization-demo"
        run: |
          python -c "
          from huggingface_hub import HfApi
          api = HfApi()
          api.upload_folder(
              folder_path='.',
              repo_id='$SPACE_NAME',
              repo_type='space',
          )
          "
